version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
      - frontend
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - './backend:/app'
  frontend:
    build: ./frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'

# services:
#   api:
#     build: ./backend
#     container_name: api_backend
#     ports:
#       - '3001:3001'
#   client:
#     build: ./frontend
#     container_name: client_frontend
#     ports:
#       - '3000:3000'
#   mysqldb:
#     image: mysql
#     restart: always
#     environment:
#       - MYSQL_ROOT_PASSWORD=whaticket
#       - MYSQL_DATABASE=cashdb
#     ports:
#       - '3306:3306'
#     volumes:
#       - db:/var/lib/mysql

networks:
    default:
        driver: bridge

volumes: 
  db: